.classpath
Won't start in eclipse otherwise
=> Add missing jar to classpath

lib/src/kbaserelationengine/events/AccessGroupStatus.java, lib/src/kbaserelationengine/events/reconstructor/WSStatusEventReconstructorImpl.java, lib/src/kbaserelationengine/events/storage/MongoDBStatusEventStorage.java, lib/src/kbaserelationengine/main/MainObjectProcessor.java, lib/src/kbaserelationengine/tools/RESKETools.java, lib/src/kbaserelationengine/tools/RESKEToolsConfig.java, lib/src/kbaserelationengine/tools/Utils.java, lib/src/kbaserelationengine/tools/WorkspaceEventGenerator.java, reske_tools.cfg.example, test/src/kbaserelationengine/events/reconstructor/WSStatusEventReconstructorTest.java, test/src/kbaserelationengine/events/storage/MongoDBStatusEventStorageTest.java, test/src/kbaserelationengine/queue/test/ObjectStatusEventQueueTest.java
Instead of placing records directly in mongo, use the event storage API.
Would prefer to do something similar with workspace but dependency hell prevents that for now.
Also updated the WS storage code to use the 3.0 mongo API.
Also also added a workspace blacklist config & CLI parameter.
=> TASK-894 Use the event storage API rather than contacting mongo directly + ws blacklist

lib/src/kbaserelationengine/main/MainObjectProcessor.java, lib/src/kbaserelationengine/search/ElasticIndexingStorage.java, lib/src/kbaserelationengine/search/IndexingStorage.java, test/src/kbaserelationengine/search/test/ElasticIndexingStorageTest.java, test/src/kbaserelationengine/test/common/TestCommon.java
Not clear how to handle admin access group on a delete
=> TASK-895 Add undelete object event & fix delete object

KBaseSearchEngine.spec, Makefile, deploy.cfg, kbase.yml, lib/src/kbaserelationengine/main/MainObjectProcessor.java, lib/src/kbasesearchengine/AccessFilter.java, lib/src/kbasesearchengine/GetObjectsInput.java, lib/src/kbasesearchengine/GetObjectsOutput.java, lib/src/kbasesearchengine/KBaseSearchEngineClient.java, lib/src/kbasesearchengine/KBaseSearchEngineServer.java, lib/src/kbasesearchengine/KeyDescription.java, lib/src/kbasesearchengine/ListTypesInput.java, lib/src/kbasesearchengine/ListTypesOutput.java, lib/src/kbasesearchengine/MatchFilter.java, lib/src/kbasesearchengine/MatchValue.java, lib/src/kbasesearchengine/ObjectData.java, lib/src/kbasesearchengine/Pagination.java, lib/src/kbasesearchengine/PostProcessing.java, lib/src/kbasesearchengine/SearchObjectsInput.java, lib/src/kbasesearchengine/SearchObjectsOutput.java, lib/src/kbasesearchengine/SearchTypesInput.java, lib/src/kbasesearchengine/SearchTypesOutput.java, lib/src/kbasesearchengine/SortingRule.java, lib/src/kbasesearchengine/TypeDescriptor.java, scripts/run_async.sh, test/src/kbaserelationengine/main/test/PerformanceTester.java, test/src/kbaserelationengine/test/KBaseRelationEngineServerTest.java
$ kb-sdk rename KBaseSearchEngine
Changing /home/crusherofheads/localgit/KBaseSearchEngine/kbase.yml
Changing /home/crusherofheads/localgit/KBaseSearchEngine/Makefile
Moving
/home/crusherofheads/localgit/KBaseSearchEngine/KBaseRelationEngine.spec
->
/home/crusherofheads/localgit/KBaseSearchEngine/KBaseSearchEngine.spec
Changing /home/crusherofheads/localgit/KBaseSearchEngine/deploy.cfg
Changing
/home/crusherofheads/localgit/KBaseSearchEngine/scripts/run_async.sh
Moving
/home/crusherofheads/localgit/KBaseSearchEngine/lib/src/kbaserelationengine/AccessFilter.java
->
/home/crusherofheads/localgit/KBaseSearchEngine/lib/src/kbasesearchengine/AccessFilter.java
Moving
/home/crusherofheads/localgit/KBaseSearchEngine/lib/src/kbaserelationengine/GetObjectsInput.java
-> …
=> Rename to KBaseSearchEngine

lib/src/kbasesearchengine/events/handler/EventHandler.java, lib/src/kbasesearchengine/events/handler/ResolvedReference.java, lib/src/kbasesearchengine/events/handler/WorkspaceEventHandler.java, lib/src/kbasesearchengine/main/MainObjectProcessor.java, lib/src/kbasesearchengine/parse/KeywordParser.java
Still some workspace specific code in there, but slowly being moved into the right spot
=> Refactor more workspace specific code behind handler abstraction

lib/src/kbasesearchengine/KBaseSearchEngineServer.java, lib/src/kbasesearchengine/events/exceptions/FatalIndexingException.java, lib/src/kbasesearchengine/events/exceptions/IndexingException.java, lib/src/kbasesearchengine/events/exceptions/IndexingExceptionUncheckedWrapper.java, lib/src/kbasesearchengine/events/exceptions/RetriableIndexingException.java, lib/src/kbasesearchengine/events/exceptions/UnprocessableEventIndexingException.java, lib/src/kbasesearchengine/events/exceptions/package-info.java, lib/src/kbasesearchengine/events/handler/EventHandler.java, lib/src/kbasesearchengine/events/handler/WorkspaceEventHandler.java, lib/src/kbasesearchengine/main/MainObjectProcessor.java, lib/src/kbasesearchengine/queue/ObjectStatusEventIterator.java, lib/src/kbasesearchengine/queue/ObjectStatusEventQueue.java, test/src/kbasesearchengine/main/test/MainObjectProcessorTest.java, test/src/kbasesearchengine/queue/test/ObjectStatusEventQueueTest.java
First crack at refactoring error handling in the indexing loop. Needs a lot more work.
=> TASK-1075 indexer error handling pt 1 of ?

lib/src/kbasesearchengine/events/storage/MongoDBStatusEventStorage.java, lib/src/kbasesearchengine/events/storage/StatusEventStorage.java, lib/src/kbasesearchengine/main/MainObjectProcessor.java, lib/src/kbasesearchengine/queue/ObjectStatusEventIterator.java, lib/src/kbasesearchengine/queue/ObjectStatusEventQueue.java, test/src/kbasesearchengine/queue/test/ObjectStatusEventQueueTest.java
Next: search & destroy unchecked exceptions
=> TASK-1075 handle the last of the checked exceptions in the index loop

lib/src/kbasesearchengine/events/handler/EventHandler.java, lib/src/kbasesearchengine/events/handler/WorkspaceEventHandler.java, lib/src/kbasesearchengine/main/MainObjectProcessor.java, lib/src/kbasesearchengine/tools/SearchTools.java
Note type of error - fatal, unexpected, retry
Log parent event
=> Clean up logging

lib/src/kbasesearchengine/events/StatusEvent.java, lib/src/kbasesearchengine/events/StatusEventType.java, lib/src/kbasesearchengine/events/exceptions/Retrier.java, lib/src/kbasesearchengine/events/exceptions/RetryLogger.java, lib/src/kbasesearchengine/events/handler/EventHandler.java, lib/src/kbasesearchengine/events/handler/WorkspaceEventHandler.java, lib/src/kbasesearchengine/events/storage/MongoDBStatusEventStorage.java, lib/src/kbasesearchengine/events/storage/StatusEventCursor.java, lib/src/kbasesearchengine/events/storage/StatusEventStorage.java, lib/src/kbasesearchengine/main/IndexerCoordinator.java, lib/src/kbasesearchengine/queue/StatusEventIterator.java, lib/src/kbasesearchengine/queue/StatusEventQueue.java, lib/src/kbasesearchengine/tools/SearchTools.java, lib/src/kbasesearchengine/tools/WorkspaceEventGenerator.java, test/src/kbasesearchengine/events/exceptions/RetrierTest.java, test/src/kbasesearchengine/main/test/MainObjectProcessorTest.java, test/src/kbasesearchengine/main/test/PerformanceTester.java, test/src/kbasesearchengine/queue/test/ObjectStatusEventQueueTest.java
Events are for more than just objects
=> Rename ObjectStatus* to Status*

build.xml, lib/src/kbasesearchengine/events/handler/SourceData.java, lib/src/kbasesearchengine/events/handler/WorkspaceEventHandler.java, lib/src/kbasesearchengine/search/ElasticIndexingStorage.java, test/src/kbasesearchengine/test/events/handler/SourceDataTest.java, test/src/kbasesearchengine/test/search/ElasticIndexingStorageTest.java
=> Rework SourceData to use optionals + tests

lib/src/kbasesearchengine/main/IndexerCoordinator.java, lib/src/kbasesearchengine/main/IndexerWorker.java, test/src/kbasesearchengine/test/integration/IndexerIntegrationTest.java
Simplifies the code quite a bit and eliminates thread.sleep() calls. Will make integrating the queue a bit easier I think.
=> TASK-1160 Use modern executor for scheduling repeated tasks

build.xml, lib/src/kbasesearchengine/events/ObjectEventQueue.java, lib/src/kbasesearchengine/events/exceptions/NoSuchEventException.java, test/src/kbasesearchengine/test/events/ObjectEventQueueTest.java, test/src/kbasesearchengine/test/events/exceptions/ExceptionTest.java
Also extract NoSuchEventException so it can be used elsewhere.
=> TASK-1160 Add a couple of helper methods to the object queue

lib/src/kbasesearchengine/parse/KeywordParser.java, lib/src/kbasesearchengine/system/IndexingRules.java, lib/src/kbasesearchengine/system/ObjectTypeParsingRules.java, lib/src/kbasesearchengine/system/ValidationException.java
Need to validate inputs before writing tests for keyword parser.
=> TASK-1196 - Rules validation

build.xml, lib/src/kbasesearchengine/events/AccessGroupEventQueue.java, lib/src/kbasesearchengine/events/ObjectEventQueue.java, test/src/kbasesearchengine/test/events/AccessGroupEventQueueTest.java, test/src/kbasesearchengine/test/events/ObjectEventQueueTest.java
Test coverage is 100%
This is another big PR, but it's mostly greenfield again and so easier to read.
=> TASK-1160 Add access group level queue

lib/src/kbasesearchengine/events/AccessGroupEventQueue.java, test/src/kbasesearchengine/test/events/AccessGroupEventQueueTest.java
Missing access group event type from set
=> TASK-1160 Fix bug in access group event queue

build.xml, lib/src/kbasesearchengine/events/AccessGroupEventQueue.java, lib/src/kbasesearchengine/events/EventQueue.java, lib/src/kbasesearchengine/events/ObjectEventQueue.java, lib/src/kbasesearchengine/events/storage/MongoDBStatusEventStorage.java, lib/src/kbasesearchengine/events/storage/StatusEventStorage.java, lib/src/kbasesearchengine/main/IndexerCoordinator.java, lib/src/kbasesearchengine/main/IndexerWorker.java, lib/src/kbasesearchengine/tools/SearchTools.java, test/src/kbasesearchengine/test/events/storage/MongoDBStatusEventStorageTest.java, test/src/kbasesearchengine/test/integration/IndexerIntegrationTest.java, test/src/kbasesearchengine/test/main/IndexerCoordinatorTest.java
Ew, this is way bigger than I thought.
=> TASK-1160 integrate event queue into indexer coordinator

lib/src/kbasesearchengine/main/IndexerCoordinator.java, test/src/kbasesearchengine/test/main/IndexerCoordinatorTest.java
Also refactor the event cycle to reduce method size and improve
readability
=> TASK-1160 Add logging for event state changes

lib/src/kbasesearchengine/tools/SearchTools.java, search_tools.cfg.example
Executor threads are supposed to be non-daemon but the workers shut down
anyway
=> TASK-1160 Make coordinator and worker stay up

lib/src/kbasesearchengine/parse/ValueCollector.java
Code simplification
Note some of the changes are whitespace only.
=> Remove unused booleans.

build.xml, lib/src/kbasesearchengine/parse/IdMapper.java, test/src/kbasesearchengine/test/integration/IndexerWorkerIntegrationTest.java, test/src/kbasesearchengine/test/main/IndexerWorkerIntegrationTest.java
make clear it's an integration test, not a unit test.
=> Rename Indexer worker test

lib/src/kbasesearchengine/main/IndexerWorker.java, test/src/kbasesearchengine/test/integration/IndexerWorkerIntegrationTest.java, test/src/kbasesearchengine/test/main/PerformanceTester.java
many public methods that were not used publicly and don't need to be
=> TASK-1266 Reduce IndexerWorker API

lib/src/kbasesearchengine/main/IndexerCoordinator.java, lib/src/kbasesearchengine/main/IndexerWorker.java, lib/src/kbasesearchengine/main/Stoppable.java, lib/src/kbasesearchengine/tools/SearchTools.java, test/src/kbasesearchengine/test/integration/IndexerIntegrationTest.java, test/src/kbasesearchengine/test/main/IndexerCoordinatorTest.java
before letting the process die.
=> Make coordinator and worker wait for task to stop

.gitignore, lib/src/kbasesearchengine/main/IndexerWorker.java
=> TASK-1266 Remove side effect from parseObjects function

lib/src/kbasesearchengine/events/ObjectEventQueue.java, lib/src/kbasesearchengine/parse/KeywordParser.java, lib/src/kbasesearchengine/system/IndexingRules.java, lib/src/kbasesearchengine/system/ObjectTypeParsingRules.java, lib/src/kbasesearchengine/system/TransformType.java
Move checking the transform type into the build stage rather than a
later validate stage, and handle the parsing in the containing class
=> TASK-1266 make transform type an enum

test/src/kbasesearchengine/test/search/ElasticIndexingStorageTest.java
Checks that saving different versions of the same type with incompatible
fields works
=> SCT-178 Add elastic test for versions

Makefile, build.xml
Get rid of some annoying dependencies on the old dev_container based development environment, and allow properties/variables to pick up values from environment variables.
=> Begone devcontainer

lib/src/kbasesearchengine/common/JsonTokenUtil.java, lib/src/kbasesearchengine/search/ElasticIndexingStorage.java
Warnings have been accumulating in the codebase; this commit fixes all
that Eclipse detects.
Also makes warning suppression more specific - adds suppression to
variables rather than methods.
=> Clean up warnings

lib/src/kbasesearchengine/tools/SearchTools.java
No console if run headless.
Headless mode needs testing.
=> Handle headless indexer & worker, attempt 1

lib/src/kbasesearchengine/tools/WorkspaceEventGenerator.java
tested manually
@briehl - needs review
=> SCT-58 Ignore temp narratives in event generator

.classpath, build.xml, lib/src/kbasesearchengine/tools/SearchTools.java, lib/src/kbasesearchengine/tools/search_spec.yaml.template, test/src/kbasesearchengine/test/tools/SearchToolsTest.java, test/src/kbasesearchengine/test/tools/createSpec.yaml
The CLI argument parsing & handling portion was tested manually. Need to add tests for that at some point, but not right now.
=> SCT-328 Add CLI minimal spec generator

lib/src/kbasesearchengine/search/ElasticIndexingStorage.java
There are currently two indexObject?() methods in
ElasticIndexingStorage, one for a single object and one for an object and
sub objects. Only the latter is actually used in the indexing code; the
former is only used for tests.
The method implementations were starting to diverge as changes were made
to the 'real' method, so the code was changed so the single object
method now delegates to the multiple object method.
This means there is a performance hit since the multiple object method
writes a temp file and the single object method does not, but this only
affects tests.
=> Clean up diverging indexObject methods

.travis.yml, test/src/kbasesearchengine/test/common/FileUtilTest.java
Might take a few tries to get this working
=> Update travis config

lib/src/kbasesearchengine/main/IndexerWorker.java, lib/src/kbasesearchengine/main/SearchMethods.java, lib/src/kbasesearchengine/parse/KeywordParser.java, lib/src/kbasesearchengine/parse/ParsedObject.java, lib/src/kbasesearchengine/search/ElasticIndexingStorage.java, lib/src/kbasesearchengine/search/IndexingStorage.java, lib/src/kbasesearchengine/search/MatchFilter.java, test/src/kbasesearchengine/test/integration/IndexerWorkerIntegrationTest.java, test/src/kbasesearchengine/test/main/IndexerWorkerTest.java, test/src/kbasesearchengine/test/main/PerformanceTester.java, test/src/kbasesearchengine/test/search/ElasticIndexingStorageTest.java
Only at ElasticIndexingStorage level at this point, API comes next.
=> SCT-404 Add ability to exclude subobjs from search to IndexingStorage

.classpath
Apparently some instances of eclipse can't handle the absolute path.
=> Fix class path

deployment/jettybase/start.d/deploy.ini, deployment/jettybase/start.d/request.ini
More stuff that didn't get committed
=> Missing INI files needed!

lib/src/kbasesearchengine/main/IndexerWorker.java, lib/src/kbasesearchengine/tools/SearchTools.java, lib/src/kbasesearchengine/tools/SearchToolsConfig.java, lib/src/kbasesearchengine/tools/WorkspaceEventGenerator.java, search_tools.cfg.example, test/src/kbasesearchengine/test/integration/IndexerIntegrationTest.java, test/src/kbasesearchengine/test/integration/IndexerWorkerIntegrationTest.java, test/src/kbasesearchengine/test/main/IndexerWorkerTest.java
Tested manually since core code changes are trivial. Will add better
tests later.
=> SCT-427 add worker codes to the UI

build.xml, lib/src/kbasesearchengine/tools/SearchTools.java
A bit Q&D for now, tested manually
```
1518214933606 2018-02-09T22:22:13.606Z Moved event 5a7e1f15b281e02ec153c101 NEW_VERSION WS:2/2/3 from UNPROC to READY
1518215051559 2018-02-09T22:24:11.559Z Retriable error in indexer, retry 1: kbasesearchengine.events.exceptions.FatalRetriableIndexingException: Failed getting events: Exception opening socket
1518215051559 2018-02-09T22:24:11.559Z Error: 
kbasesearchengine.events.exceptions.FatalRetriableIndexingException: Failed getting events: Exception opening socket
```
=> Add timestamps to logs

.travis.yml, build/push2dockerhub.sh
Have Travis push the debug branch to Dockerhub on merges.
=> debug branch

build.xml, lib/src/kbasesearchengine/main/IndexerCoordinator.java
=> Add debug logs, iteration 1

lib/src/kbasesearchengine/events/StoredStatusEvent.java, lib/src/kbasesearchengine/events/storage/MongoDBStatusEventStorage.java, lib/src/kbasesearchengine/events/storage/StatusEventStorage.java, lib/src/kbasesearchengine/tools/WorkspaceEventGenerator.java, test/src/kbasesearchengine/test/events/StoredStatusEventTest.java, test/src/kbasesearchengine/test/events/storage/MongoDBStatusEventStorageTest.java
=> SCT-568 Add stored by & time when storing events

lib/src/kbasesearchengine/events/AccessGroupEventQueue.java, lib/src/kbasesearchengine/events/StoredStatusEvent.java, lib/src/kbasesearchengine/events/storage/MongoDBStatusEventStorage.java, lib/src/kbasesearchengine/events/storage/StatusEventStorage.java, lib/src/kbasesearchengine/tools/WorkspaceEventGenerator.java, test/src/kbasesearchengine/test/events/AccessGroupEventQueueTest.java, test/src/kbasesearchengine/test/events/StoredStatusEventTest.java, test/src/kbasesearchengine/test/events/storage/MongoDBStatusEventStorageTest.java
* Events can now record store time and stored by
* Queue initialization failures provide more information
=> Add debug improvements from develop

lib/src/kbasesearchengine/events/AccessGroupEventQueue.java, lib/src/kbasesearchengine/events/StoredStatusEvent.java, test/src/kbasesearchengine/test/events/AccessGroupEventQueueTest.java, test/src/kbasesearchengine/test/events/StoredStatusEventTest.java
Also adds toString() to StoredStatusEvents which will be useful elsewhere.
=> SCT-568 Add more information to queue init failures

lib/src/kbasesearchengine/events/AccessGroupEventQueue.java, lib/src/kbasesearchengine/events/EventQueue.java, lib/src/kbasesearchengine/main/IndexerCoordinator.java
Add a size method that doesn't depend on the memoization of the size
Add a few more printouts
=> Add more diagnostics

lib/src/kbasesearchengine/main/SearchMethods.java, test/src/kbasesearchengine/test/common/TestCommon.java, test/src/kbasesearchengine/test/integration/SearchAPIIntegrationTest.java, test/src/kbasesearchengine/test/main/SearchMethodsTest.java
=> [SCT-586]Add type

lib/src/kbasesearchengine/main/SearchMethods.java, test/src/kbasesearchengine/test/integration/SearchAPIIntegrationTest.java, test/src/kbasesearchengine/test/main/SearchMethodsTest.java
-returns version of type as well
=> [SCT-586] update to include type version

.classpath, build.xml, lib/src/kbasesearchengine/authorization/TemporaryAuth2Client.java, lib/src/kbasesearchengine/main/SearchMethods.java, test/src/kbasesearchengine/test/integration/SearchAPIIntegrationTest.java
Expanded from the client in https://github.com/kbase/KBaseSearchEngine/pull/178
=> SCT-409 SCT-410 Add an auth client

lib/src/kbasesearchengine/KBaseSearchEngineServer.java, lib/src/kbasesearchengine/authorization/TemporaryAuth2Client.java, lib/src/kbasesearchengine/main/NarrativeInfoDecorator.java, test/src/kbasesearchengine/test/integration/SearchAPIIntegrationTest.java, test/src/kbasesearchengine/test/main/NarrativeInfoDecoratorTest.java
Adapted from https://github.com/kbase/KBaseSearchEngine/pull/178
=> SCT-409 SCT-410 Add display names to the narrative decoration

lib/src/kbasesearchengine/KBaseSearchEngineServer.java, lib/src/kbasesearchengine/main/TemporaryNarrativePruner.java, test/src/kbasesearchengine/test/integration/SearchAPIIntegrationTest.java
Fields are just enormous strings and are useless
=> Prune narrative data

lib/src/kbasesearchengine/main/IndexerWorker.java
Getting weird errors:
java.lang.IllegalStateException: Duplicate key kbasesearchengine.search.ObjectData@2ab1c576
Note that ObjectData is the *value*
=> Revert stream to regular map construction

lib/src/kbasesearchengine/search/ElasticIndexingStorage.java, test/src/kbasesearchengine/test/ElasticPayloadAnanlyzerTester.java
All client usage now occurs in one method.
=> SCT-626 Refactor elastic client usage

lib/src/kbasesearchengine/events/exceptions/ErrorType.java, lib/src/kbasesearchengine/events/handler/WorkspaceEventHandler.java, lib/src/kbasesearchengine/main/IndexerWorker.java, lib/src/kbasesearchengine/parse/GUIDNotFoundException.java, lib/src/kbasesearchengine/parse/KeywordParser.java, test/src/kbasesearchengine/test/events/handler/WorkspaceEventHandlerTest.java, test/src/kbasesearchengine/test/main/IndexerWorkerTest.java, test/src/kbasesearchengine/test/parse/KeyWordParserTest.java
rounds out error types for the most common errors.
=> SCT-624 Add DELETED and GUID_NOT_FOUND error types

lib/src/kbasesearchengine/main/IndexerWorker.java
listObjectTypeParsingRules no longer throws any checked exceptions so
wrapping it in a retrier is useless. Also relocate the method near to
the one place it's used.
Trying to simplify the exception handling as much as possible before adding the exceptions to the DB.
=> SCT-624 Simplify object type supported check

build.xml, lib/src/kbasesearchengine/events/AccessGroupEventQueue.java, lib/src/kbasesearchengine/events/ChildStatusEvent.java, lib/src/kbasesearchengine/events/ObjectEventQueue.java, lib/src/kbasesearchengine/events/StatusEventWithId.java, lib/src/kbasesearchengine/events/StoredChildStatusEvent.java, lib/src/kbasesearchengine/events/StoredStatusEvent.java, lib/src/kbasesearchengine/events/exceptions/NoSuchEventException.java, lib/src/kbasesearchengine/events/handler/WorkspaceEventHandler.java, lib/src/kbasesearchengine/events/storage/MongoDBStatusEventStorage.java, lib/src/kbasesearchengine/events/storage/StatusEventStorage.java, lib/src/kbasesearchengine/main/IndexerCoordinator.java, lib/src/kbasesearchengine/main/IndexerWorker.java, test/src/kbasesearchengine/test/events/ChildStatusEventTest.java, test/src/kbasesearchengine/test/events/StoredChildStatusEventTest.java, test/src/kbasesearchengine/test/events/StoredStatusEventTest.java, test/src/kbasesearchengine/test/events/storage/MongoDBStatusEventStorageTest.java, test/src/kbasesearchengine/test/integration/IndexerWorkerIntegrationTest.java, test/src/kbasesearchengine/test/main/IndexerCoordinatorTest.java
This will allow saving errors along with child events in a future PR.
=> SCT-624 Store child events

lib/src/kbasesearchengine/events/StoredStatusEvent.java, lib/src/kbasesearchengine/events/storage/MongoDBStatusEventStorage.java, lib/src/kbasesearchengine/events/storage/StatusEventStorage.java, test/src/kbasesearchengine/test/events/StoredStatusEventTest.java, test/src/kbasesearchengine/test/events/storage/MongoDBStatusEventStorageTest.java
As opposed to child events in the prior PR.
=> SCT-624 Store errors with standard events

lib/src/kbasesearchengine/main/IndexerWorker.java, test/src/kbasesearchengine/test/main/IndexerWorkerTest.java
Can be confusing when fatal & non-fatal retries are interleaved
=> Highlight fatal retries in logs

resources/types/OntologyTerm.yaml, test/src/kbasesearchengine/test/parse/data/ontology01.json.properties, test/src/kbasesearchengine/test/search/ElasticIndexingStorageTest.java
I'm adding a spec for the OntologyTerm sub objects. This is probably not going to be used in the UI yet but for conditions data I'll need the ability to find ontology terms that match a users's supplied text. 
I've also added a test to ElasticIndexingStorageTest.java
=> Ontology type
