lib/src/kbaserelationengine/main/MainObjectProcessor.java
test/src/kbaserelationengine/main/test/MainObjectProcessorTest.java
test/src/kbaserelationengine/test/common/TestCommon.java

The deleted method is unused. Evidence: 1) Eclipse search doesn't find
any usage, 2) code compiles. The method is deleted because its name
does not reflect what it does and the indexer should not be making
changes to the workspace anyway.

Don't hard code WS version in tests

---

lib/src/kbaserelationengine/search/ElasticIndexingStorage.java

The script complication circuit breaker activates *a lot* when cloning a
large workspace (cloning code is in another branch ATM). This PR fixes the
scripts to only need to compile once when first used, rather than
possibly, depending on the parameters, on every invocation.
There are now up to 10 script compilations possible as long as the scripts stay cached,
so the compliations / min circuit breaker should no longer be tripped.
Tests now pass.
TODO:

Fix script complication fails

---

dependencies.json
lib/src/kbaserelationengine/events/handler/WorkspaceEventHandler.java
lib/src/kbaserelationengine/main/MainObjectProcessor.java
lib/src/kbaserelationengine/parse/ObjectParser.java
lib/src/kbaserelationengine/search/ElasticIndexingStorage.java
lib/src/kbaserelationengine/search/IndexingStorage.java
lib/src/workspace/ListWorkspaceIDsParams.java
lib/src/workspace/ListWorkspaceIDsResults.java
lib/src/workspace/ObjectSaveData.java
lib/src/workspace/WorkspaceClient.java
test/src/kbaserelationengine/main/test/MainObjectProcessorTest.java
test/src/kbaserelationengine/test/common/TestCommon.java
test/src/kbaserelationengine/test/controllers/workspace/WorkspaceController.java

NOTE: no changes were made to the reconstructor
Added a test.token2 property required in test.cfg to separate the
standard and admin users.
TODO
for that yet

WIP: Switch to ws admin methods

---

.classpath
KBaseRelationEngine.spec
build.xml
lib/src/kbaserelationengine/events/AccessGroupCache.java
lib/src/kbaserelationengine/events/AccessGroupProvider.java
lib/src/kbaserelationengine/events/WorkspaceAccessGroupProvider.java
lib/src/kbaserelationengine/events/storage/MongoDBStatusEventStorage.java
lib/src/kbaserelationengine/main/MainObjectProcessor.java
test/src/kbaserelationengine/events/AccessGroupCacheTest.java
test/src/kbaserelationengine/events/storage/MongoDBStatusEventStorageTest.java
test/src/kbaserelationengine/test/common/TestCommon.java

Adds a cache for access group IDs per user. Expires based on
configurable time in cache and cache size. Cache is source agnostic and
wraps and presents the same AccessGroupProvider interface.
Now queries the workspace for private access groups rather than maintaining a local copy.
Tested manually.
On extremely limited data, search appears to be pretty fast - 31ms on a cache miss vs. 15ms on a cache hit when running RESKE and the workspace locally.
TODO:

TASK-895 Add access group id cache & workspace provider implementation

---

lib/src/kbasesearchengine/KBaseSearchEngineServer.java
lib/src/kbasesearchengine/events/handler/WorkspaceEventHandler.java
lib/src/kbasesearchengine/main/MainObjectProcessor.java
test/src/kbasesearchengine/main/test/MainObjectProcessorTest.java
test/src/kbasesearchengine/main/test/PerformanceTester.java

* Use the object timestamp instead of the event timestamp when indexing objects
* Switch to dependency injection for MOP creation. Should make splitting the indexer out of MOP much easier. Also makes testing and component swapping easier.

Refactor MOP to use dependency injection, fix workspace timestamp

---

lib/src/kbasesearchengine/events/StatusEvent.java
lib/src/kbasesearchengine/events/handler/ResolvedReference.java
lib/src/kbasesearchengine/events/handler/WorkspaceEventHandler.java
lib/src/kbasesearchengine/events/storage/OldMongoDBStatusEventStorage.java
lib/src/kbasesearchengine/main/IndexerCoordinator.java
lib/src/kbasesearchengine/search/ElasticIndexingStorage.java
lib/src/kbasesearchengine/search/IndexingStorage.java
lib/src/kbasesearchengine/tools/WorkspaceEventGenerator.java
test/src/kbasesearchengine/events/exceptions/RetrierTest.java
test/src/kbasesearchengine/main/test/MainObjectProcessorTest.java
test/src/kbasesearchengine/main/test/PerformanceTester.java
test/src/kbasesearchengine/search/test/ElasticIndexingStorageTest.java

Adds a builder for status event in preparation for removing the id field
and adding a processing status field.
Also switch long, which is ambiguous, to Instant, and use Optionals for
nullable values.

Refactor statusevent w/ builder

---

lib/src/kbasesearchengine/events/StatusEvent.java
lib/src/kbasesearchengine/events/StatusEventID.java
lib/src/kbasesearchengine/events/StatusEventWithID.java
lib/src/kbasesearchengine/events/exceptions/Retrier.java
lib/src/kbasesearchengine/events/exceptions/RetryLogger.java
lib/src/kbasesearchengine/events/handler/EventHandler.java
lib/src/kbasesearchengine/events/handler/WorkspaceEventHandler.java
lib/src/kbasesearchengine/events/storage/OldMongoDBStatusEventStorage.java
lib/src/kbasesearchengine/events/storage/OldStatusEventStorage.java
lib/src/kbasesearchengine/events/storage/StatusEventCursor.java
lib/src/kbasesearchengine/main/IndexerCoordinator.java
lib/src/kbasesearchengine/queue/StatusEventIterator.java
lib/src/kbasesearchengine/queue/StatusEventQueue.java
lib/src/kbasesearchengine/tools/WorkspaceEventGenerator.java
test/src/kbasesearchengine/events/exceptions/RetrierTest.java
test/src/kbasesearchengine/main/test/MainObjectProcessorTest.java
test/src/kbasesearchengine/main/test/PerformanceTester.java

Now stores sub events in database and generates an ID for the sub event.
Does not yet check to avoid storing duplicate events or reprocessing
successful sub events.
Removed the id field from StatusEvent (now in StatusEventWithID).
Remove a not particularly helpful level of indirection by marking event
processing state in the storage system with a direct storage call,
rather than via an iterator then a queue then the storage system

TASK-1161 Store sub events in database

---

lib/src/kbasesearchengine/events/StoredStatusEvent.java
lib/src/kbasesearchengine/events/storage/MongoDBStatusEventStorage.java
lib/src/kbasesearchengine/events/storage/StatusEventStorage.java
lib/src/kbasesearchengine/main/IndexerWorker.java
test/src/kbasesearchengine/test/events/StoredStatusEventTest.java
test/src/kbasesearchengine/test/events/exceptions/RetrierTest.java
test/src/kbasesearchengine/test/events/storage/MongoDBStatusEventStorageTest.java
test/src/kbasesearchengine/test/main/IndexerWorkerTest.java
test/src/kbasesearchengine/test/main/PerformanceTester.java

Allows the coordinator to detect workers that have hung or failed and
log warnings (or something else)

Add update time to event record

---

build.xml
lib/src/kbasesearchengine/events/ObjectEventQueue.java
lib/src/kbasesearchengine/events/StatusEventType.java
lib/src/kbasesearchengine/main/IndexerCoordinator.java
lib/src/kbasesearchengine/main/IndexerWorker.java
test/src/kbasesearchengine/test/events/ObjectEventQueueTest.java
test/src/kbasesearchengine/test/events/exceptions/RetrierTest.java

An access group level queue will wrap, initialize, and control multiple object level queues.
This is really big, but it's almost all greenfield code and so is easier to read.
Either @arfathpasha or @tianhao-gu could review this, but tian doesn't have write access to I can't add him to the reviewer list.

Add object level queue

---

lib/src/kbasesearchengine/events/storage/MongoDBStatusEventStorage.java
lib/src/kbasesearchengine/events/storage/StatusEventStorage.java
lib/src/kbasesearchengine/main/IndexerCoordinator.java
lib/src/kbasesearchengine/main/IndexerWorker.java
lib/src/kbasesearchengine/tools/SearchTools.java
test/src/kbasesearchengine/test/events/storage/MongoDBStatusEventStorageTest.java

Add option to specify current state of event when changing state based
on ID. This prevents the indexer switching an in process event back to
the ready state.

Add safety check to event state changes

---

lib/src/kbasesearchengine/main/IndexerCoordinator.java
lib/src/kbasesearchengine/main/IndexerWorker.java
test/src/kbasesearchengine/test/main/IndexerCoordinatorTest.java

currently logs 1/hour for events that have been running for > 1 hour.

Add logging for delayed events

---

build.xml
lib/src/kbasesearchengine/events/ChildStatusEvent.java
lib/src/kbasesearchengine/events/StatusEventWithId.java
lib/src/kbasesearchengine/events/StoredStatusEvent.java
lib/src/kbasesearchengine/events/exceptions/Retrier.java
lib/src/kbasesearchengine/events/exceptions/RetryLogger.java
lib/src/kbasesearchengine/events/handler/EventHandler.java
lib/src/kbasesearchengine/events/handler/WorkspaceEventHandler.java
lib/src/kbasesearchengine/events/storage/MongoDBStatusEventStorage.java
lib/src/kbasesearchengine/main/IndexerCoordinator.java
lib/src/kbasesearchengine/main/IndexerWorker.java
test/src/kbasesearchengine/test/events/ChildStatusEventTest.java
test/src/kbasesearchengine/test/events/StoredStatusEventTest.java
test/src/kbasesearchengine/test/events/exceptions/RetrierTest.java
test/src/kbasesearchengine/test/main/IndexerCoordinatorTest.java
test/src/kbasesearchengine/test/main/IndexerWorkerTest.java
test/src/kbasesearchengine/test/main/PerformanceTester.java

The changes here, although numerous, are actually pretty simple and just
entail wrapping child StatusEvents in ChildStatusEvent which associates
the parent ID with the child event.
There is currently no reasonable test suite for the
WorkspaceEventHandler or the IndexerWorker and building one would take a
really long time so manually tested for now. The only real logical
changes (other than removing code) are some minor logging changes.
Child events are no longer stored in the database, but these changes
make it pretty easy to do so if we want to later.
Also make max returned events in mongostatusstorage a constant

TASK-1160 Refactor child event handling

---

.gitignore
lib/src/kbasesearchengine/main/IndexerWorker.java

Adds retries for attempts to set event state in the storage system. Also
a refactor to DRY up the code a little and make the exception handling
somewhat less incomprehensible.
Manually tested stuff that's possible to test. Need to add unit tests
later.

Add retries for worker db calls

---

lib/src/kbasesearchengine/system/IndexingRules.java
lib/src/kbasesearchengine/system/ObjectTypeParsingRules.java

Not used. Can be set, but is never accessed in the code.

TASK-1266 Remove constant value from indexing rules

---

build.xml
lib/src/kbasesearchengine/main/SearchMethods.java
lib/src/kbasesearchengine/parse/KeywordParser.java
lib/src/kbasesearchengine/parse/ObjectParser.java
lib/src/kbasesearchengine/search/ElasticIndexingStorage.java
lib/src/kbasesearchengine/system/IndexingRules.java
lib/src/kbasesearchengine/system/LocationTransformType.java
lib/src/kbasesearchengine/system/ObjectTypeParsingRules.java
lib/src/kbasesearchengine/system/Transform.java
lib/src/kbasesearchengine/system/TransformType.java
resources/types/Genome.json
resources/types/Narrative.json
resources/types/PairedEndLibrary.json
test/src/kbasesearchengine/test/search/ElasticIndexingStorageTest.java
test/src/kbasesearchengine/test/system/IndexingRulesTest.java
test/src/kbasesearchengine/test/system/TransformTest.java

* immutable
* fluent builder
* constraints enforced at build time rather than later in various places in the code
* defaults set at build time rather than calculated later in various places in the code
* separate out transform class
* no nulls returned from API
Also removed the lookup.oname transform from Genome.json because that inserts a mutable object name into an index that will not get updated. If we want to find Genomes by the the name of their source Assembly we need some other solution, not this.

SCT-157 Refactor indexing rules

---

build.xml
lib/src/kbasesearchengine/parse/KeywordParser.java
lib/src/kbasesearchengine/parse/ObjectParser.java
lib/src/kbasesearchengine/system/IndexingRules.java
lib/src/kbasesearchengine/system/ObjectTypeParsingRules.java
lib/src/kbasesearchengine/system/ObjectTypeParsingRulesUtils.java
lib/src/kbasesearchengine/system/Transform.java
lib/src/kbasesearchengine/system/TypeFileStorage.java
test/src/kbasesearchengine/test/search/ElasticIndexingStorageTest.java
test/src/kbasesearchengine/test/system/ObjectTypeParsingRulesTest.java

* immutable
* fluent builder
* constraints enforced at build time rather than later in various places in the code
* defaults set at build time rather than calculated later in various places in the code
* no nulls returned from API
* split secondary utility code that builds OTPRs from various input sources into a separate class for cohesivity of the core OTPR value class
* rename methods to better reflect fuction

SCT-157 Refactor ObjectTypeParsingRules

---

build.xml
lib/src/kbasesearchengine/parse/ObjectParser.java
lib/src/kbasesearchengine/parse/ParsedObject.java
lib/src/kbasesearchengine/system/ObjectTypeParsingRules.java
test/src/kbasesearchengine/test/main/IndexerWorkerTest.java

It turns out that the 'bug' was as designed. When creating GUIDs for subobjects, if the parsing code can't find an id for the subobject, as a default it uses the path to the subobject, including the leading slash, in the parent object as an id for the last portion of the GUID (e.g. WS:1/2/3:AssemblyContig/[id]).
The problem is that this behavior occurs if the id can't be found for any reason, including if there are unintentional errors in the spec. Things I've found so far that can cause the default behavior include:
1) leaving out primary-id-path
2) misspelling primary-id-path
3) misspelling the value of primary-id-path
4) not including an indexing rule that causes the value of the key at primary-id-path to be extracted
5) including an indexing rule with an error such that the key does …

SCT-157 Fix subobject ID mangling bug

---

build.xml
lib/src/kbasesearchengine/events/handler/CloneableWorkspaceClient.java
lib/src/kbasesearchengine/events/handler/CloneableWorkspaceClientImpl.java
lib/src/kbasesearchengine/events/handler/WorkspaceEventHandler.java
lib/src/kbasesearchengine/tools/SearchTools.java
test/src/kbasesearchengine/test/events/handler/CloneableWorkspaceClientImplTest.java
test/src/kbasesearchengine/test/integration/IndexerIntegrationTest.java
test/src/kbasesearchengine/test/integration/IndexerWorkerIntegrationTest.java

This is simply so the clone operation can produce a mocked workspace
client.

Add a clonable WS client

---

build.xml
lib/src/kbasesearchengine/main/IndexerWorker.java
lib/src/kbasesearchengine/main/SearchMethods.java
lib/src/kbasesearchengine/parse/KeywordParser.java
lib/src/kbasesearchengine/parse/ObjectParser.java
lib/src/kbasesearchengine/search/ElasticIndexingStorage.java
lib/src/kbasesearchengine/search/IndexingStorage.java
lib/src/kbasesearchengine/system/ObjectTypeParsingRules.java
lib/src/kbasesearchengine/system/ObjectTypeParsingRulesUtils.java
lib/src/kbasesearchengine/system/SearchObjectType.java
lib/src/kbasesearchengine/system/TypeFileStorage.java
resources/types/Assembly.json
resources/types/AssemblyContig.json
resources/types/Genome.yaml
resources/types/GenomeFeature.json
resources/types/Narrative.json
resources/types/PairedEndLibrary.json
resources/types/SeedOntologyTerm.json
resources/types/SingleEndLibrary.json
test/src/kbasesearchengine/test/data/EmptyAType.json
test/src/kbasesearchengine/test/integration/IndexerWorkerIntegrationTest.java
test/src/kbasesearchengine/test/main/IndexerWorkerTest.java
test/src/kbasesearchengine/test/main/PerformanceTester.java
test/src/kbasesearchengine/test/search/ElasticIndexingStorageTest.java
test/src/kbasesearchengine/test/system/ObjectTypeParsingRulesTest.java
test/src/kbasesearchengine/test/system/SearchObjectTypeTest.java

First step of making the search system aware of search type versions.
Lots still to do, and the version is ignored in most places.
* Update elastic search to take the version into account for indexes and
returned data
* Update TypeMappings to take the version of the type into account
* Update TypeFileStorage
* Add versions to type files (multiple versions per file), remove version key
* Add target type version to GUID transform

SCT-178 Add a version int to search types

---

lib/src/kbasesearchengine/search/ElasticIndexingStorage.java
lib/src/kbasesearchengine/system/ObjectTypeParsingRulesUtils.java
lib/src/kbasesearchengine/system/TypeFileStorage.java
resources/types/Assembly.json
resources/types/AssemblyContig.json
resources/types/Genome.yaml
resources/types/GenomeFeature.json
resources/types/Narrative.json
resources/types/PairedEndLibrary.json
resources/types/SeedOntologyTerm.json
resources/types/SingleEndLibrary.json
test/src/kbasesearchengine/test/data/EmptyAType.json
test/src/kbasesearchengine/test/search/ElasticIndexingStorageTest.java

Files now support multiple versions per type in one file.
TODO:
* Need to add some tests here, but adding cases for incorrectly
formatted files is a real pain. Preferably add JSONSchema check for file
contents after a YAML parse.
* Make TypeMappings version aware.

SCT-178 Add versions to search spec files

---

lib/src/kbasesearchengine/system/TypeFileStorage.java
lib/src/kbasesearchengine/system/TypeMapping.java
lib/src/kbasesearchengine/system/YAMLTypeMappingParser.java
resources/typemappings/GenomeAndAssembly.yaml.example
resources/types/Genome.yaml
test/src/kbasesearchengine/test/data/EmptyAType.json
test/src/kbasesearchengine/test/system/TypeMappingTest.java

Tested the type mapping parser manually against the one mapping
available.
TODO:
* Write tests for TypeFileStorage. It's too complicated at this point to
not have tests.
* Write a test for elastic indexing storage with a type with versions
with incompatible fields.

SCT-178 Make type mappings version aware

---

lib/src/kbasesearchengine/parse/SubObjectExtractor.java
lib/src/kbasesearchengine/search/ElasticIndexingStorage.java
lib/src/kbasesearchengine/system/ObjectTypeParsingRules.java
test/src/kbasesearchengine/test/data/NoIndexingRules.spec
test/src/kbasesearchengine/test/data/NoIndexingRules.yaml
test/src/kbasesearchengine/test/integration/IndexerIntegrationTest.java
test/src/kbasesearchengine/test/integration/IndexerWorkerIntegrationTest.java
test/src/kbasesearchengine/test/search/ElasticIndexingStorageTest.java
test/src/kbasesearchengine/test/system/ObjectTypeParsingRulesTest.java

Allows for easily setting up minimal indexes for types where we don't want to take the time to develop a spec but do want to index the general object properties like name, etc.
Note most of the SubObjectExtractor changes are whitespace.
ElasticIndexingStorage would silently drop objects with no indexing
rules, while the logger made it appear as though everything worked.
also removed the EIS.skipFullJson field, which was unused and always
false.
also also some minor cleanup.

SCT-328 Allow search specs without indexing rules

---

.classpath
build.xml
test/src/kbasesearchengine/test/common/TestCommon.java
test/src/kbasesearchengine/test/events/handler/CloneableWorkspaceClientImplTest.java
test/src/kbasesearchengine/test/integration/IndexerIntegrationTest.java
test/src/kbasesearchengine/test/integration/IndexerWorkerIntegrationTest.java

No longer any need for tokens in the test config when running ant test directly.
`ant test -Djars.dir=/home/crusherofheads/localgit/jars/lib/jars -Dtest.cfg=test_local/test.cfg`
Running kb-sdk test still requires a token.

Use embedded auth server for tests

---

lib/src/kbasesearchengine/events/StoredStatusEvent.java
lib/src/kbasesearchengine/events/storage/MongoDBStatusEventStorage.java
lib/src/kbasesearchengine/main/IndexerWorker.java
lib/src/kbasesearchengine/search/ElasticIndexingStorage.java
test/src/kbasesearchengine/test/events/AccessGroupEventQueueTest.java
test/src/kbasesearchengine/test/events/EventQueueTest.java
test/src/kbasesearchengine/test/events/ObjectEventQueueTest.java
test/src/kbasesearchengine/test/events/StoredStatusEventTest.java
test/src/kbasesearchengine/test/events/exceptions/ExceptionTest.java
test/src/kbasesearchengine/test/events/exceptions/RetrierTest.java
test/src/kbasesearchengine/test/events/storage/MongoDBStatusEventStorageTest.java
test/src/kbasesearchengine/test/integration/IndexerWorkerIntegrationTest.java
test/src/kbasesearchengine/test/main/IndexerCoordinatorTest.java
test/src/kbasesearchengine/test/main/PerformanceTester.java

In preparation for adding the ability to assign events to a subset of workers.
Worker codes are currently unused elsewhere.

SCT-427 Add builder for StoredStatusEvent with worker codes

---

lib/src/kbasesearchengine/events/storage/MongoDBStatusEventStorage.java
lib/src/kbasesearchengine/events/storage/StatusEventStorage.java
lib/src/kbasesearchengine/main/IndexerWorker.java
lib/src/kbasesearchengine/tools/WorkspaceEventGenerator.java
test/src/kbasesearchengine/test/events/storage/MongoDBStatusEventStorageTest.java

Adds codes to mongoDB class such that events can be assigned to workers.
TODO: Add to UI (next PR)

SCT-427 add worker codes

---

lib/src/kbasesearchengine/events/AccessGroupEventQueue.java
lib/src/kbasesearchengine/events/ObjectEventQueue.java
test/src/kbasesearchengine/test/events/AccessGroupEventQueueTest.java
test/src/kbasesearchengine/test/events/EventQueueTest.java
test/src/kbasesearchengine/test/events/ObjectEventQueueTest.java

Currently version level events don't block each other in the queue, and
unlimited version level events can run at the same time per object. It
turns out that the ElasticIndexingStorage class runs a script that
touches all versions of an object when a NEW_VERSION event is processed,
and this is causing 409 conflict errors when processing two versions of
the same object at the same time.
Alter the queue so that only one NEW_VERSION event can run per object at
once.

SCT-508  Alter queue so verison level events block each other 

---

lib/src/kbasesearchengine/search/ElasticIndexingStorage.java
test/src/kbasesearchengine/test/integration/SearchAPIIntegrationTest.java

- account for elasticsearch returning null for highlight instead of empty map
- appears to occur somewhat consistently for GUIDs and sporadically for other search queries.

[SCT-593] NullPointerException running search_objects query

---

lib/src/kbasesearchengine/search/ElasticIndexingStorage.java
test/src/kbasesearchengine/test/search/ElasticIndexingStorageTest.java

Can now specify any object property to sort on
Note that object names will need to be changed to the keyword type and
reindexed for sorting on object names to work.

SCT-587 Refactor Elastic sorting code

---

lib/src/kbasesearchengine/events/AccessGroupEventQueue.java
lib/src/kbasesearchengine/events/EventQueue.java
lib/src/kbasesearchengine/events/ObjectEventQueue.java
test/src/kbasesearchengine/test/events/AccessGroupEventQueueTest.java
test/src/kbasesearchengine/test/events/EventQueueTest.java
test/src/kbasesearchengine/test/events/ObjectEventQueueTest.java
test/src/kbasesearchengine/test/main/IndexerCoordinatorTest.java

The coordinator currently has no way to know which events in the DB are in memory without passing all the event IDs into the DB query, and so continually loads the same UNPROC events over and over, duplicating queued events and eventually filling the queue. 
This change makes the queue ignore events that already exist in the queue based on the event id. The same UNPROC events will get pulled from the DB over and over, but will not be added to the queue. As before, events that have been set to READY will no longer get pulled.
This does mean that the effective load size will be less than requested, since some of the events will be ignored. Since the oldest events will still get loaded before newer events, things should work ok.
A pathological example might be if 5000 events are in the …

Fix coordinator load bug

---

lib/src/kbasesearchengine/search/ElasticIndexingStorage.java

2m isn't enough for large genomes like sorghum
Later could split the loads into smaller packages
https://www.elastic.co/guide/en/elasticsearch/client/java-rest/current/java-rest-low-usage-initialization.html

Bump elastic client timeout to 10m

---

lib/src/kbasesearchengine/tools/SearchTools.java
lib/src/kbasesearchengine/tools/WorkspaceEventGenerator.java

Adds the ability to select only the last version when generating events.
Tested manually in general.
Specifically tested by manually changing the batch size set in the Versions class to 10, 11, 12, and 13, which overlap an object id change.

Select last version only when generating events

---

resources/types/MediaCompound.yaml
test/src/kbasesearchengine/test/parse/ObjectParserTest.java
test/src/kbasesearchengine/test/parse/media01.json.properties
test/src/kbasesearchengine/test/search/ElasticIndexingStorageTest.java

This addresses the log issues like this one:
1518923196918 2018-02-18T03:06:36.918Z Error processing event for event NEW_VERSION with parent ID 5a875ac0e4b00d0e6e4d29d3: kbasesearchengine.events.exceptions.UnprocessableEventIndexingException: Could not find the subobject id for one or more of the subobjects for object WS:28269/16/8 when applying search specification MediaCompound_1

Change media compound subobject key

---

build.xml
lib/src/kbasesearchengine/main/IndexerWorker.java
lib/src/kbasesearchengine/parse/KeywordParser.java
test/src/kbasesearchengine/test/parse/KeyWordParserTest.java
test/src/kbasesearchengine/test/search/ElasticIndexingStorageTest.java

Currently throws an IndexOutOfBounds, which is not recognized by the exception handling system.

Throw correct exception when location array is missing information

---

lib/src/kbasesearchengine/main/IndexerWorker.java
lib/src/kbasesearchengine/search/ElasticIndexingStorage.java
lib/src/kbasesearchengine/search/IndexingConflictException.java
lib/src/kbasesearchengine/search/IndexingStorage.java
test/src/kbasesearchengine/test/ElasticPayloadAnanlyzerTester.java
test/src/kbasesearchengine/test/main/IndexerWorkerTest.java
test/src/kbasesearchengine/test/search/ElasticIndexingStorageTest.java

They're not great in that they mean the code isn't handling indexing
correctly in some cases, but shutting the worker down and leaving events
in a stuck state is worse.
This doesn't fix the root cause of the problem but means there's no
known errors that cause a worker shutdown where the worker continuing
does no further harm.
Unfortunately reliably testing elastic conflicts is going to be very difficult (at least I can't think of a simple way to do it) so we'll have to test in CI.

SCT-626 Treat elastic conflict exceptions as non-fatal

---

lib/src/kbasesearchengine/events/exceptions/ErrorType.java
lib/src/kbasesearchengine/events/exceptions/FatalIndexingException.java
lib/src/kbasesearchengine/events/exceptions/FatalRetriableIndexingException.java
lib/src/kbasesearchengine/events/exceptions/IndexingException.java
lib/src/kbasesearchengine/events/exceptions/RetriableIndexingException.java
lib/src/kbasesearchengine/events/exceptions/Retrier.java
lib/src/kbasesearchengine/events/exceptions/RetriesExceededIndexingException.java
lib/src/kbasesearchengine/events/exceptions/UnprocessableEventIndexingException.java
lib/src/kbasesearchengine/events/handler/WorkspaceEventHandler.java
lib/src/kbasesearchengine/events/storage/MongoDBStatusEventStorage.java
lib/src/kbasesearchengine/main/IndexerCoordinator.java
lib/src/kbasesearchengine/main/IndexerWorker.java
lib/src/kbasesearchengine/parse/ContigLocationException.java
lib/src/kbasesearchengine/parse/KeywordParser.java
test/src/kbasesearchengine/test/common/TestCommon.java
test/src/kbasesearchengine/test/events/exceptions/RetrierTest.java
test/src/kbasesearchengine/test/events/handler/WorkspaceEventHandlerTest.java
test/src/kbasesearchengine/test/main/IndexerCoordinatorTest.java
test/src/kbasesearchengine/test/main/IndexerWorkerTest.java
test/src/kbasesearchengine/test/parse/KeyWordParserTest.java
test/src/kbasesearchengine/test/search/ElasticIndexingStorageTest.java

Adds an error type to errors that reach the portion of the worker code
where events get updated in the DB. Currently does nothing, but future
PRs will add the error type to the DB on a failed event. This will allow
for filtering on the error type when doing error analysis, rather than
having to filter on arbitrary error strings.

SCT-642 Add error type to errors

---

lib/src/kbasesearchengine/main/IndexerWorker.java
test/src/kbasesearchengine/test/common/TestCommon.java
test/src/kbasesearchengine/test/integration/IndexerWorkerIntegrationTest.java
test/src/kbasesearchengine/test/main/IndexerWorkerTest.java
test/src/kbasesearchengine/test/main/PerformanceTester.java

Makes the parent method of the method formerly known as processOneEvent
the method exposed for testing rather than pOE.
1) Allows for testing event skipping.
2) Will respond correctly when asked to process an event for which no
search specs exist rather than doing some undefined weird thing.
Next PR: test event skipping.

SCT-624 Allow easy testing of more of the event processing code

---

lib/src/kbasesearchengine/events/StoredChildStatusEvent.java
lib/src/kbasesearchengine/events/storage/MongoDBStatusEventStorage.java
lib/src/kbasesearchengine/events/storage/StatusEventStorage.java
test/src/kbasesearchengine/test/events/StoredChildStatusEventTest.java
test/src/kbasesearchengine/test/events/storage/MongoDBStatusEventStorageTest.java

Changes the child event storage interface to require an error to be stored along with the event.

SCT-624 Store errors with child events

---

lib/src/kbasesearchengine/events/StoredChildStatusEvent.java
lib/src/kbasesearchengine/main/IndexerWorker.java
lib/src/kbasesearchengine/parse/KeywordParser.java
test/src/kbasesearchengine/test/main/IndexerWorkerTest.java

Sets up the glue code that connects all the changes in previous PRs (e.g. new exception types & error codes, error storage with events) such that indexing errors are now stored in the database along with their associated events.

SCT-624 Store indexing exceptions in DB

---

RELEASE_NOTES.md
lib/src/kbasesearchengine/events/handler/WorkspaceEventHandler.java
lib/src/kbasesearchengine/main/IndexerWorker.java
lib/src/kbasesearchengine/search/ElasticIndexingStorage.java
test/src/kbasesearchengine/test/search/ElasticIndexingStorageTest.java

When a subobject array in a parent object is empty, the ES code will
insert a record with no `key.*` properties with the parent guid in the
index for the type. E.g. if a genome has no features (which really
should never happen, but there are examples in the wild), ES will insert
a record with the parent object's GUID in the genomefeature index, which
is bad, because searches for the parent object will find it and it'll
have the wrong type, which can screw up recursive indexing in some
cases.
The reason ES does this is to support specs with no indexing rules, such
that the general object properties of a type can be indexed even if
we're not interested in the contents. We want the behavior for parent
objects, but not subobjects.

SCT-717 Fix error when no subobjects are found
